version: '3.8'

services:
  # INI SERVICE BARU UNTUK API ANDA
  api: 
    container_name: presensi_api
    restart: always
    build: .  # <-- Ini memberitahu Docker untuk mencari Dockerfile di folder ini
    ports:
      - "3001:3001" # Ganti 3001 dengan port API Anda
    environment:
      # Anda bisa pindahkan koneksi database ke sini
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_DATABASE=presensi_app
      - DB_PORT=5432
      - PORT=3001
    depends_on:
      - db # <-- Ini memberitahu API untuk menunggu database siap

  # INI SERVICE DATABASE YANG SUDAH ANDA BUAT
  db:
    image: postgres:15 
    container_name: presensi_db
    restart: always
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=presensi_app
    volumes:
      - ./db_data:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  db_data: