version: '3.8' # (Atribut ini bisa dihapus jika Docker mengeluh)

services:
  db:
    image: ankane/pgvector:latest
    container_name: presensi_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: presensi_app
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    image: agussyuhada/mi-alfaizein:api
    container_name: presensi_api
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
      - face-service

  face-service:
    image: agussyuhada/mi-alfaizein:face-service
    container_name: face_service
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    image: agussyuhada/mi-alfaizein:frontend
    container_name: presensi_frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    depends_on:
      - server
    volumes:
      - ./certbot/www:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  db_data: